---
- name: Secure SSH server, set up key-based login, change root password
  hosts: linux
  become: true
  vars:
    key_dir: "../keys"
    file_dir: "../files"
  vars_prompt:
    - name: root_pass_enc
      prompt: Enter new root pass
      private: true
      encrypt: sha512_crypt
      confirm: true
      unsafe: true

  tasks:
  - name: Ensure .ssh directory exists
    file:
      path: "/home/{{ ssh_user }}/.ssh"
      state: directory
      owner: "{{ ssh_user }}"
      group: "{{ ssh_user }}"
      mode: '0700'

  - name: Load keys as authorised keys
    authorized_key:
      user: "{{ ssh_user }}"
      state: present
      manage_dir: yes
      key: "{{ lookup('pipe', 'cat {{ key_dir }}/*.pub') }}"
      exclusive: yes

  - name: Harden sshd_config
    template:
      src: "{{ file_dir }}/sshd_config"
      dest: /etc/ssh/sshd_config
      owner: root
      mode: "0600"
      validate: /usr/sbin/sshd -t -f %s

  - name: Restart SSH service
    service:
      name: sshd
      state: restarted
      enabled: true

  - name: Change root password
    user:
      name: "{{ ssh_user }}"
      password: "{{ root_pass_enc }}"
