---
- name: Secure SSH server and set up key-based login from a directory of keys
  hosts: linux
  become: true
  vars:
    key_dir: "../keys"
    file_dir: "../files"

  tasks:

  - name: Ensure .ssh directory exists
    file:
      path: "/home/{{ ssh_user }}/.ssh"
      state: directory
      owner: "{{ ssh_user }}"
      group: "{{ ssh_user }}"
      mode: '0700'

  - name: Load keys as authorised keys
    authorized_key:
      user: "{{ ssh_user }}"
      state: present
      manage_dir: yes
      key: "{{ lookup('file', '{{ key_dir }}/id_ed25519.pub') }}"

  - name: Harden sshd_config
    template:
      src: "{{ file_dir }}/sshd_config"
      dest: /etc/ssh/sshd_config
      owner: root
      mode: "0600"
      validate: /usr/sbin/sshd -t -f %s

  - name: Restart SSH service
    service:
      name: sshd
      state: restarted
      enabled: true

